openapi: 3.0.0
info:
  version: 1.0.0-oas3
  title: Geography
  description: |-
    Get countries, states, and provinces.
    ### OAuth Scopes 

    |  **UI Name** | **Permission** | **Parameter** |
    | --- | --- | --- | 
    |  Information & Settings | modify | `store_v2_information` | 
    |  Information & Settings | read-only | `store_v2_information_read_only` |
paths:
  '/stores/{store_hash}/v2/countries':
    get:
      description: 'Get a list of all countries available. A country or territory, identifiable by an ISO 3166 country code.'
      summary: Get All Countries
      parameters:
        - name: Accept
          in: header
          required: true
          description: ''
          schema:
            type: string
            default: application/json
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
            default: application/json
        - name: page
          in: query
          required: false
          description: Number of pages
          schema:
            type: number
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: limit
          in: query
          required: false
          description: Count per page
          schema:
            type: number
            exclusiveMinimum: false
            exclusiveMaximum: false
        - in: query
          name: country
          schema:
            type: string
        - in: query
          name: country_iso2
          schema:
            type: string
        - in: query
          name: country_iso3
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/countryCollection_Resp'
      tags:
        - Countries
    parameters:
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/{id}':
    get:
      description: 'Returns a single *Country*.  Gets a country. A country or territory, identifiable by an ISO 3166 country code.'
      summary: Get a Country
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the country.
          schema:
            type: integer
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: Accept
          in: header
          required: true
          description: ''
          schema:
            type: string
            default: application/json
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
            default: application/json
      responses:
        '200':
          $ref: '#/components/responses/countriesResponse'
      tags:
        - Countries
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/{country_id}/states':
    get:
      description: |-
        Returns a list of *States* belonging to a *Country*. 
        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get All Country's States
      parameters:
        - name: country_id
          in: path
          required: true
          description: Id of the country
          schema:
            type: integer
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: Accept
          in: header
          required: true
          description: ''
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
        - name: state
          in: query
          required: false
          description: Name of the state/province.
          schema:
            type: string
        - name: state_abbreviation
          in: query
          required: false
          description: Abbreviation for the state/province.
          schema:
            type: string
        - name: page
          in: query
          required: false
          description: Number of pages
          schema:
            type: number
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: limit
          in: query
          required: false
          description: Count per page
          schema:
            type: number
            exclusiveMinimum: false
            exclusiveMaximum: false
      responses:
        '200':
          $ref: '#/components/responses/countriesStatesCollectionResponse'
      tags:
        - States
    parameters:
      - name: country_id
        in: path
        required: true
        schema:
          type: string
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/{country_id}/states/{id}':
    get:
      description: |-
        Returns a *State*. 
        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get a Country's State
      parameters:
        - name: country_id
          in: path
          required: true
          description: Id of the country
          schema:
            type: integer
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: id
          in: path
          required: true
          description: Id of the states
          schema:
            type: integer
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: Accept
          in: header
          required: true
          description: ''
          schema:
            type: string
            default: application/json
        - name: Content-Type
          in: header
          required: true
          description: ''
          schema:
            type: string
            default: application/json
      responses:
        '200':
          $ref: '#/components/responses/countriesStatesResponse'
      x-unitTests: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
      tags:
        - States
    parameters:
      - name: country_id
        in: path
        required: true
        schema:
          type: string
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
      - schema:
          type: string
        name: id
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/count':
    get:
      responses:
        '200':
          $ref: '#/components/responses/countResponse'
      summary: Get a Count of All Countries
      tags:
        - Countries
      operationId: countriesCount
      description: Returns a count of all countries.
    parameters:
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/states/count':
    get:
      responses:
        '200':
          $ref: '#/components/responses/countResponse'
      summary: Get a Count of All States
      tags:
        - States
      description: Returns a count of all states.
    parameters:
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/states':
    get:
      responses:
        '200':
          $ref: '#/components/responses/countriesStatesCollectionResponse'
      summary: Get All States
      tags:
        - States
      description: Returns a list of all states.
    parameters:
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
  '/stores/{store_hash}/v2/countries/{country_id}/states/count':
    get:
      responses:
        '200':
          $ref: '#/components/responses/countResponse'
      summary: 'Get a Count of Countryâ€™s States '
      tags:
        - States
      description: Returns a count of a country's states.
    parameters:
      - name: country_id
        in: path
        required: true
        schema:
          type: string
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
security:
  - X-Auth-Token: []
tags:
  - name: Countries
  - name: States
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
servers:
  - url: 'https://api.bigcommerce.com'
    variables:
      store_hash:
        default: unknown
components:
  responses:
    countriesResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/country_Full'
          examples:
            response:
              value:
                id: 1
                country: Afghanistan
                country_iso2: AF
                country_iso3: AFG
                states:
                  url: 'https://api.bigcommerce.com/stores/h10wocxy6s/v2/countries/1/states'
                  resource: /countries/1/states
    countriesStatesResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/countriesState_Full'
    countryCollection_Resp:
      description: ''
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/country_Full'
          example:
            - id: 1
              country: Afghanistan
              country_iso2: AF
              country_iso3: AFG
              states:
                url: 'https://api.bigcommerce.com/stores/store_hash/v2/countries/1/states'
                resource: /countries/1/states
            - id: 2
              country: Albania
              country_iso2: AL
              country_iso3: ALB
              states:
                url: 'https://api.bigcommerce.com/stores/store_hash/v2/countries/2/states'
                resource: /countries/2/states
    countriesStatesCollectionResponse:
      description: ''
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/countriesState_Full'
    countResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/count_Full'
          examples:
            response:
              value:
                count: 241
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      name: X-Auth-Token
      in: header
      description: ''
  schemas:
    country_Full:
      title: country_Full
      example:
        id: 13
        country: Australia
        country_iso2: AU
        country_iso3: AUS
        states:
          url: 'https://api.bigcommerce.com/stores/{store_hash}/v2/countries/13/states'
          resource: /countries/13/states
      allOf:
        - type: object
          properties:
            id:
              type: integer
              description: Id of the country.
              example: 13
        - $ref: '#/components/schemas/country_Base'
        - type: object
          properties:
            states:
              $ref: '#/components/schemas/countriesStates_Full'
      x-internal: false
    countriesStates_Full:
      title: countriesStates_Full
      type: object
      properties:
        url:
          description: ''
          example: 'https://api.bigcommerce.com/stores/{store_hash}/v2/countries/13/states'
          type: string
        resource:
          description: ''
          example: /countries/13/states
          type: string
      description: Refers to the `states` object return in `GET` countries requests.
      x-internal: false
    countriesState_Full:
      title: countriesState_Full
      example:
        id: 208
        state: Australian Capital Territory
        state_abbreviation: ACT
        country_id: 13
      type: object
      properties:
        id:
          description: Numeric ID of the state/province.
          example: 208
          type: integer
        state:
          description: Name of the state/province.
          example: Australian Capital Territory
          type: string
        state_abbreviation:
          description: Abbreviation for the state/province.
          example: ACT
          type: string
        country_id:
          description: Numeric ID of the stateâ€™s/provinceâ€™s associated country.
          example: 13
          type: integer
      description: 'Refers to the state returned in `GET` states requests. '
      x-internal: false
    country_Base:
      type: object
      title: country_Base
      properties:
        country:
          type: string
          example: Australia
          description: Country name.
        country_iso2:
          type: string
          description: 2-letter country code.
          example: AU
        country_iso3:
          type: string
          description: 3-letter country code.
          example: AUS
      x-internal: false
    count_Full:
      type: object
      properties:
        count:
          type: integer
          minimum: 1
      x-internal: false
