openapi: 3.0.0
info:
  title: Tax Provider Connection
  version: '3'
  description: 'Manage the connection between a merchant''s BigCommerce store and a third party tax provider. For more information, see [Tax Provider API Overview](/api-docs/providers/tax).'
paths:
  '/stores/{store_hash}/v3/tax/providers/{provider_id}/connection':
    get:
      summary: Get Connection Status
      description: |
        Retrieve the connection status of the specified tax provider in the context of a store.

        <!-- theme: info -->
        > #### Note
        > * Requires **read** permissions on the **Information and Settings** scope.
      operationId: provider-connection-get
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/response-connection'
            application/json:
              examples:
                response:
                  value:
                    data:
                      username: MyConnectedTaxProviderAccount
                      configured: true
        '404':
          description: Provider does not exist
      security:
        - X-Auth-Token: []
      tags:
        - Tax Provider Connection
    delete:
      summary: Delete a Connection
      description: |
        Remove any previously set basic connection credentials for the specified provider. If the specified provider is the active tax provider on the store, the store's active tax provider will be reset to BigCommerce Manual Tax. It is suggested to call this endpoint during a single-click app [uninstall callback](/api-docs/apps/guide/callbacks#uninstall-callback).

        <!-- theme: info -->
        > #### Note
        > * This operation will be logged in [Store Logs](https://support.bigcommerce.com/s/article/Using-Store-Logs) under **Staff Actions**.
        > * Requires **write** permissions on the **Information and Settings** [scope](/api-docs/getting-started/authentication/rest-api-authentication#oauth-scopes).
      operationId: provider-connection-delete
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/response-connection'
            application/json:
              examples:
                response:
                  value:
                    data:
                      username: MyDisconnectedTaxProviderAccount
                      configured: false
        '404':
          description: Provider does not exist
      security:
        - X-Auth-Token: []
      tags:
        - Tax Provider Connection
    put:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response-connection'
              examples:
                response:
                  value:
                    data:
                      username: MyUpdatedTaxProviderAccount
                      configured: true
        '404':
          description: Provider does not exist
        '422':
          description: 'Unprocessable Entity, will include a specific error message referencing the issue.'
      description: |-
        Set the HTTP Basic Authentication credentials and the (optional) profile for the specified provider. 
        
        The configured `username` and `password` will be used to authenticate each API request to the Tax Provider from the associated store.
        The tax provider's `profile` will be included in the url for Tax Provider API endpoints. 

        <!-- theme: info -->
        > #### Note
        > * This operation will be logged in [Store Logs](https://support.bigcommerce.com/s/article/Using-Store-Logs) under **Staff Actions**.
        > * Requires **write** permissions on the **Information and Settings** [scope](/api-docs/getting-started/authentication/rest-api-authentication#oauth-scopes).
      summary: Update a Connection
      operationId: provider-connection-put
      tags:
        - Tax Provider Connection
      security:
        - X-Auth-Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Public identifying information representing a unique account on the tax provider's infrastructure. Should not contain any personal identifying information (e.g. a personal email address).
                  example: MyTaxProviderAccount
                password:
                  type: string
                  example: h6eSgKLN72q7jYTW
                profile:
                  type: string
                  example: your_app_name
                  description: Optional field that allows merchants to customize Tax Provider API endpoint URLs. Only available for supporting providers.
        description: 'Basic authentication information, associated with a merchant account on the third-party tax provider''s infrastructure.'
        x-examples:
          application/json:
            username: MyTaxProviderAccount
            password: h6eSgKLN72q7jYTW
            profile: test-profile
    parameters:
      - name: provider_id
        in: path
        required: true
        schema:
          type: string
        description: 'The Tax Provider''s `provider_id` provided by BigCommerce after the provider [shares their provider details](/api-docs/providers/tax#sharing-provider-details-with-bigcommerce).'
      - schema:
          type: string
        name: store_hash
        in: path
        required: true
security:
  - X-Auth-Token: []
tags:
  - name: Tax Provider Connection
servers:
  - url: 'https://api.bigcommerce.com'
components:
  parameters:
    provider_id:
      name: Tax Provider ID
      in: path
      description: Unique key that identifies the Tax Provider on the BigCommerce platform.
      required: true
      schema:
        type: string
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      name: X-Auth-Token
      in: header
      description: |-
        ### OAuth Scopes
        |  **UI Name** | **Permission** | **Parameter** |
        | --- | --- | --- |
        |  Information & Settings | modify | `store_v2_information` |
        |  Information & Settings | read-only | `store_v2_information_read_only` |

        ### Headers

        |Header|Parameter|Description|
        |-|-|-|
        |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|

        ### Example

        ```http
        GET /stores/{store_hash}/v3/catalog/summary
        host: api.bigcommerce.com
        Content-Type: application/json
        X-Auth-Token: {access_token}
        ```

        * For more information on Authenticating BigCommerce APIs, see: [Authentication](/api-docs/getting-started/authentication).
  schemas:
    response-connection:
      type: object
      title: Connection Status
      properties:
        data:
          type: object
          properties:
            username:
              type: string
              description: Identifies a unique account on the external tax provider infrastructure. May be used to reconcile the two platforms.
            configured:
              type: boolean
              description: |-
                Describes whether the stored credentials are considered complete and configured, ready to be used for Tax Provider API requests.

                Merchants may enable any **configured** tax provider for storefront tax quotation.
      x-internal: false
